### ISSUE TITLE
proper steps to execute?

### ISSUE THREAD

**Issue by fragger98** [MarkusRabe/cadet#8]
Hey! I am using UBUNTU to run your tool. I did the cloning of your repository into my local device. I tried to execute the example you gave in Readme.md. 
I did the following steps
1.  cloned the repository into my PC
2. created a text editor and pasted the QDIMACS format code as it is into the text editor and saved it as new.qdimacs.( does that work?)
3. used the command ./cadet new.qdimacs to execute the file. 
This did not work. I got an error 
bash: ./cadet : no such file of directory 

Can you please tell me where I am going wrong?

**Comment by MarkusRabe** [comment]
Hey fragger98,

Thanks for your interest in cadet. Some questions that may help you debug this issue:

1. Did you follow the installation instructions?
2. In which directory did you type the command?
3. In which directory did you create the file new.qdimacs? It is easiest when it is in the same directory that your binary of cadet is in.

Don't hesitate to ask if you have further questions.

Best,
Markus

**Comment by fragger98** [comment]
I have cloned your repository into my PC and the .qdimacs files that contain the example question are there in the CADET folder. I usually right click on the folder and click " open in terminal " 
once the terminal is open I type " ./cadet <filename>.qdimacs to execute the file. 
But i get this error: 
bash: ./cadet : no such file of directory

**Comment by MarkusRabe** [comment]
The reason your command is failing is that the binary "cadet" does not exist yet. You first have to compile it. Please follow the installation instructions: https://github.com/MarkusRabe/cadet#installing-cadet

The alternative is to download and use the linux binary provided in an earlier release: https://github.com/MarkusRabe/cadet/releases/download/v2.5/cadet_linux
